name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Docker containers
        run: make build  # Replace with your actual make command to build containers

      - name: Start Docker containers
        run: make up  # Replace with your actual make command to start containers

      - name: Wait for services to be ready
        run: sleep 30  # Adjust sleep time based on your service startup time

      - name: Create test database
        run: |
          docker exec -it $(docker-compose ps -q postgres) psql -U postgres -c 'CREATE DATABASE database_test;'

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test


