name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}  # Use your PostgreSQL password secret
          POSTGRES_DB: desarrollo  # Replace with your development database name
          POSTGRES_DB_TEST: database_test  # Define environment variable for test database
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Create test database
        run: |
          docker exec -it postgres psql -U postgres -c 'CREATE DATABASE database_test;'

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: make test

